# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'wHelp.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Help(object):
    def setupUi(self, Help):
        Help.setObjectName("Help")
        Help.setWindowModality(QtCore.Qt.ApplicationModal)
        Help.setEnabled(True)
        Help.resize(671, 403)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Help.sizePolicy().hasHeightForWidth())
        Help.setSizePolicy(sizePolicy)
        Help.setMinimumSize(QtCore.QSize(671, 403))
        Help.setMaximumSize(QtCore.QSize(671, 403))
        Help.setWindowOpacity(1.0)
        Help.setStyleSheet("")
        Help.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.centralwidget = QtWidgets.QWidget(Help)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.btnFechar = QtWidgets.QPushButton(self.centralwidget)
        self.btnFechar.setObjectName("btnFechar")
        self.gridLayout.addWidget(self.btnFechar, 5, 1, 1, 2)
        self.txtDeveloper = QtWidgets.QLineEdit(self.centralwidget)
        self.txtDeveloper.setEnabled(False)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.txtDeveloper.setFont(font)
        self.txtDeveloper.setStyleSheet("background-color: rgb(120, 255, 181);\n"
"color: rgb(0, 0, 0);")
        self.txtDeveloper.setAlignment(QtCore.Qt.AlignCenter)
        self.txtDeveloper.setObjectName("txtDeveloper")
        self.gridLayout.addWidget(self.txtDeveloper, 0, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 1, 1, 1)
        self.txtVersion = QtWidgets.QLineEdit(self.centralwidget)
        self.txtVersion.setEnabled(False)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.txtVersion.setFont(font)
        self.txtVersion.setStyleSheet("background-color: rgb(120, 255, 181);\n"
"color: rgb(0, 0, 0);")
        self.txtVersion.setAlignment(QtCore.Qt.AlignCenter)
        self.txtVersion.setObjectName("txtVersion")
        self.gridLayout.addWidget(self.txtVersion, 2, 2, 1, 1)
        self.labVer = QtWidgets.QLabel(self.centralwidget)
        self.labVer.setObjectName("labVer")
        self.gridLayout.addWidget(self.labVer, 2, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 3, 1, 1, 1)
        self.txtChangeLog = QtWidgets.QTextEdit(self.centralwidget)
        self.txtChangeLog.setEnabled(True)
        self.txtChangeLog.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.txtChangeLog.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.txtChangeLog.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.txtChangeLog.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.txtChangeLog.setLineWrapMode(QtWidgets.QTextEdit.NoWrap)
        self.txtChangeLog.setReadOnly(True)
        self.txtChangeLog.setObjectName("txtChangeLog")
        self.gridLayout.addWidget(self.txtChangeLog, 4, 1, 1, 2)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setMinimumSize(QtCore.QSize(150, 0))
        self.label_2.setText("")
        self.label_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 6, 1)
        Help.setCentralWidget(self.centralwidget)

        self.retranslateUi(Help)
        QtCore.QMetaObject.connectSlotsByName(Help)

    def retranslateUi(self, Help):
        _translate = QtCore.QCoreApplication.translate
        Help.setWindowTitle(_translate("Help", "Help - About"))
        self.btnFechar.setText(_translate("Help", "Fechar Help"))
        self.label_3.setText(_translate("Help", "Developer:"))
        self.labVer.setText(_translate("Help", "Version:"))
        self.label_5.setText(_translate("Help", "Changelog:"))
